'use client';

import Barcode from 'react-barcode';
import { format } from 'date-fns';

interface ChallanProps {
    invoice: any;
    student: any;
    schoolName: string;
}

// Single Copy Component
const ChallanCopy = ({ title, invoice, student, schoolName }: { title: string } & ChallanProps) => {
    return (
        <div className="border-2 border-gray-800 p-4 text-xs w-[32%] h-full flex flex-col justify-between bg-white text-black">
            <div className="text-center border-b-2 border-gray-400 pb-2 mb-2">
                <h2 className="font-bold text-lg uppercase tracking-wider">{schoolName}</h2>
                <p className="text-[10px] font-semibold">Fee Challan - {title} Copy</p>
            </div>

            <div className="space-y-1.5 mb-4">
                <div className="flex justify-between"><span>Challan No:</span> <span className="font-bold font-mono">{invoice.invoiceNo}</span></div>
                <div className="flex justify-between"><span>Due Date:</span> <span>{format(new Date(invoice.dueDate), 'dd-MMM-yyyy')}</span></div>
                <div className="flex justify-between"><span>Billing Month:</span> <span className="uppercase font-medium">{format(new Date(0, invoice.month - 1), 'MMMM yyyy')}</span></div>
            </div>

            <div className="space-y-1.5 mb-4 border-b border-gray-400 pb-2">
                <div className="flex justify-between"><span>Roll No:</span> <span className="font-medium">{student.studentRecord?.rollNumber || 'N/A'}</span></div>
                <div className="flex justify-between"><span>Name:</span> <span className="font-bold">{student.name}</span></div>
                <div className="flex justify-between"><span>Class:</span> <span>{student.studentRecord?.myClass?.name || 'N/A'}</span></div>
            </div>

            <table className="w-full mb-4">
                <thead>
                    <tr className="border-b border-gray-800 text-left">
                        <th className="py-1">Description</th>
                        <th className="text-right py-1">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {invoice.items.map((item: any) => (
                        <tr key={item.id} className="border-b border-gray-100">
                            <td className="py-1">{item.feeHead.name}</td>
                            <td className="text-right py-1">{Number(item.amount).toFixed(2)}</td>
                        </tr>
                    ))}
                </tbody>
                <tfoot>
                    <tr className="border-t-2 border-gray-800 font-bold text-sm">
                        <td className="pt-2">Total Payable</td>
                        <td className="text-right pt-2">{Number(invoice.totalAmount).toFixed(2)}</td>
                    </tr>
                </tfoot>
            </table>

            <div className="text-center mt-auto flex flex-col items-center">
                {/* Barcode Component */}
                <div className="max-w-full overflow-hidden">
                    <Barcode 
                        value={invoice.invoiceNo} 
                        width={1.2}
                        height={35}
                        fontSize={12}
                        displayValue={true} 
                        margin={0}
                    />
                </div>
                <p className="mt-4 text-[10px] text-gray-500">Generated by School System</p>
            </div>
        </div>
    );
};

export default function PrintableChallan({ invoice, student, schoolName }: ChallanProps) {
    if (!invoice || !student) return null;

    return (
        <div className="w-full bg-white p-4 hidden print:flex flex-row justify-between gap-4 h-full min-h-[200mm]">
            <ChallanCopy title="Bank" invoice={invoice} student={student} schoolName={schoolName} />
            <ChallanCopy title="School" invoice={invoice} student={student} schoolName={schoolName} />
            <ChallanCopy title="Student" invoice={invoice} student={student} schoolName={schoolName} />
        </div>
    );
}